# farzona


In [ ]:
import numpy as np

In [ ]:
x=np.array([1,5,8,9])

In [ ]:
x

array([1, 5, 8, 9])

In [ ]:
x.ndim

2

In [ ]:
y=np.array([[2,2,4],[5,0,-9]])
y

array([[ 2,  2,  4],
       [ 5,  0, -9]])

In [ ]:
y[1,1]

np.int64(0)

In [ ]:
y.ndim

2

In [ ]:
import torch

In [ ]:
x=torch.tensor([[2,2,4],[5,0,-9]])
x

tensor([[ 2,  2,  4],
        [ 5,  0, -9]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
x.ndim

2

In [ ]:
A=np.array([[0,1],[1,1]])
B=np.array([[5,1],[1,-1]])
C=A+B
C

array([[5, 2],
       [2, 0]])

In [ ]:
np.linalg.norm(A)+np.linalg.norm(B)

np.float64(7.023553429698058)

In [ ]:
D=np.array([])
D

array([], dtype=float64)

In [ ]:
np.linalg.norm(C*3)

np.float64(17.233687939614086)

In [ ]:
np.linalg.norm(C)

np.float64(5.744562646538029)

In [ ]:
A*B

array([[ 0,  1],
       [ 1, -1]])

In [ ]:
A.T

array([[0, 1],
       [1, 1]])

In [ ]:
a=5
A.dot(a)

array([[0, 5],
       [5, 5]])

In [ ]:
a.dot(A)

NameError: name 'a' is not defined

In [2]:
from sklearn.datasets import make_regression

In [3]:
X,y=make_regression(10, n_features=4, noise=10, random_state=42)

In [4]:
X

array([[ 0.76743473, -0.23413696, -0.23415337,  1.57921282],
       [-1.4123037 ,  0.31424733, -1.01283112, -0.90802408],
       [-0.46572975,  0.54256004, -0.46947439, -0.46341769],
       [-0.56228753, -1.91328024,  0.24196227, -1.72491783],
       [-1.42474819, -0.2257763 ,  1.46564877,  0.0675282 ],
       [ 1.85227818, -0.29169375, -0.60063869, -0.60170661],
       [ 0.37569802,  0.11092259, -0.54438272, -1.15099358],
       [ 0.19686124, -1.95967012,  0.2088636 , -1.32818605],
       [ 1.52302986, -0.1382643 ,  0.49671415,  0.64768854],
       [-1.22084365, -1.05771093, -0.01349722,  0.82254491]])

In [5]:
y

array([ 177.90084289, -300.31498986,  -89.83320308, -340.22625264,
         -3.73814937,   38.9407237 , -123.30816437, -256.44702895,
        241.96313341, -111.82555456])

In [6]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso